### ISSUE TITLE
Graph example doesn't compile

### ISSUE THREAD

**Issue by charleslemaire0** [tomstewart89/Geometry#16]
Hi,

I would like to use your graph mimic for our sky to telescope pipeline.
But currently the example doesn't compile on a teensy 4.0
here is the link to my project:
https://groups.io/g/TeenAstro/wiki/Home

**Comment by charleslemaire0** [comment]
it is an issue related to visual micro

**Comment by charleslemaire0** [comment]
here is the message I get:
Arduino: 1.8.19 (Windows 10), TD: 1.57, Board: "Teensy 3.2 / 3.1, Serial, 96 MHz (overclock), Faster, US English"
In file included from C:\Users\Charles\Documents\Git2\TeenAstro\libraries\Geometry\examples\PoseGraph\PoseGraph.ino:1:0:

PoseGraph.h:34: error: array must be initialized with a brace-enclosed initializer

     Geometry::Pose* transforms[max_frames][max_frames] = {NULL};
                                                           
In file included from C:\Users\Charles\Documents\Git2\TeenAstro\libraries\Geometry\examples\PoseGraph\PoseGraph.cpp:1:0:

PoseGraph.h:34: error: array must be initialized with a brace-enclosed initializer

     Geometry::Pose* transforms[max_frames][max_frames] = {NULL};

                                                               ^

array must be initialized with a brace-enclosed initializer
