### ISSUE TITLE
Compiling Geometry gives template errors with Matrix

### ISSUE THREAD

**Issue by twinotter** [tomstewart89/Geometry#6]
I've found a compilation problem in my configuration while compiling the IntegrateGyroData example.

Board: ESP32 4MB
Geometry version 1.0.0
BasicLinearAlgebrea 1.2.0 -> 2.0.0
Arduino IDE 1.8.10
Example Code: IntegrateGyroData.ino

Under BasicLinearAlgebra version 1.2.0, I get no compilation errors. When I compile with 2.0.0, I get the following errors:

```
In file included from C:\Users\The_o\Documents\Arduino\libraries\Geometry/Geometry.h:5:0,

                 from C:\Users\The_o\Documents\Arduino\libraries\arduino_174989\examples\IntegrateGyroData\IntegrateGyroData.ino:1:

C:\Users\The_o\Documents\Arduino\libraries\BasicLinearAlgebra/BasicLinearAlgebra.h:292:102: error: redeclaration of 'Matrix<rows, cols, ElemT, Array<rows, cols, ElemT> > Matrix<rows, cols, ElemT, MemT>::Inverse(int*)' may not have default arguments [-fpermissive]

 Matrix<rows,cols,ElemT,Array<rows,cols,ElemT> > Matrix<rows,cols,ElemT,MemT>::Inverse(int *res = NULL)

                                                                                                      ^

Multiple libraries were found for "Geometry.h"
 Used: C:\Users\The_o\Documents\Arduino\libraries\Geometry
 Not used: C:\Users\The_o\Documents\Arduino\libraries\arduino_174989
Multiple libraries were found for "BasicLinearAlgebra.h"
 Used: C:\Users\The_o\Documents\Arduino\libraries\BasicLinearAlgebra
exit status 1
Error compiling for board ESP32 Dev Module.
```

BTW, I'm not sure if it's related to the "multiple libraries" issue at the bottom, so I left it in the output listing. It is selecting the correct library location.

This compiles just fine if I select BasicLinearAlgebra version 1.2 (which is how I'm working around this for now).

**Comment by tomstewart89** [comment]
Hey @twinotter, looks like the compiler is taking issue with the default parameter I've defined on `Inverse`. I can't reproduce the error on my system so maybe it does have something to do with that multiple libraries issue. Try removing that second `BasicLinearAlgebra.h` in your `arduino_174989` directory and see if that clears things up

That said, the prototype for this Inverse function is pretty nasty so I might try to update it to look something like a `std::optional` in the not too distant future.

**Comment by tomstewart89** [comment]
Just as a belated follow-up here, I did indeed change the interface to the `Inverse` function, so I don't think this will be an issue in v2.0. If you have any more trouble with this or anything else in the latest release, by all means let me know!
